// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

type Comment struct {
	ID        string             `json:"id"`
	PostID    string             `json:"postId"`
	ParentID  *string            `json:"parentId,omitempty"`
	AuthorID  string             `json:"authorId"`
	Content   string             `json:"content"`
	CreatedAt string             `json:"createdAt"`
	Replies   *PaginatedComments `json:"replies"`
}

type Mutation struct {
}

type PaginatedComments struct {
	Comments   []*Comment `json:"comments"`
	TotalCount int        `json:"totalCount"`
	NextCursor *string    `json:"nextCursor,omitempty"`
}

type PaginatedPosts struct {
	Posts      []*Post `json:"posts"`
	TotalCount int     `json:"totalCount"`
	NextCursor *string `json:"nextCursor,omitempty"`
}

type Post struct {
	ID            string             `json:"id"`
	Title         string             `json:"title"`
	Content       string             `json:"content"`
	AuthorID      string             `json:"authorId"`
	AllowComments bool               `json:"allowComments"`
	CreatedAt     string             `json:"createdAt"`
	Comments      *PaginatedComments `json:"comments"`
}

type Query struct {
}

type Subscription struct {
}
